export type TableColumnWidths = Readonly<Record<string, string>>

export const tableColumnWidths = {
    server: {
        select: "4%",
        id: "7%",
        name: "14%",
        groups: "9%",
        ip: "20%",
        host_version: "7%",
        enableDDNS: "8%",
        hideForGuest: "9%",
        note: "5%",
        uuid: "5%",
        actions: "12%",
    },
    service: {
        select: "4%",
        id: "4%",
        name: "11%",
        target: "14%",
        cover: "8%",
        servers: "9%",
        type: "7%",
        duration: "6%",
        ngroup: "7%",
        triggerTask: "6%",
        failTriggerTasks: "8%",
        recoverTriggerTasks: "8%",
        actions: "8%",
    },
    cron: {
        select: "4%",
        id: "4%",
        name: "11%",
        taskType: "7%",
        scheduler: "10%",
        command: "10%",
        ngroup: "7%",
        pushSuccessful: "8%",
        cover: "7%",
        servers: "8%",
        lastExecution: "10%",
        lastResult: "6%",
        actions: "8%",
    },
    ddns: {
        select: "4%",
        id: "6%",
        name: "16%",
        enableIPv4: "7%",
        enableIPv6: "7%",
        provider: "14%",
        domains: "24%",
        maxRetries: "10%",
        actions: "12%",
    },
    nat: {
        select: "4%",
        id: "6%",
        enabled: "8%",
        name: "16%",
        serverID: "9%",
        host: "20%",
        domain: "25%",
        actions: "12%",
    },
    notification: {
        select: "4%",
        id: "8%",
        name: "18%",
        groups: "12%",
        url: "28%",
        verify_tls: "16%",
        actions: "14%",
    },
    alertRule: {
        select: "4%",
        id: "5%",
        name: "15%",
        ngroup: "9%",
        triggerMode: "9%",
        rules: "22%",
        failTriggerTasks: "9%",
        recoverTriggerTasks: "9%",
        enable: "7%",
        actions: "11%",
    },
    serverGroup: {
        select: "4%",
        id: "8%",
        name: "28%",
        servers: "44%",
        actions: "16%",
    },
    notificationGroup: {
        select: "4%",
        id: "8%",
        name: "28%",
        notifications: "44%",
        actions: "16%",
    },
    user: {
        select: "4%",
        id: "8%",
        username: "27%",
        role: "15%",
        updated_at: "30%",
        actions: "16%",
    },
    onlineUser: {
        select: "4%",
        ip: "27%",
        user_id: "15%",
        connected_at: "38%",
        actions: "16%",
    },
    waf: {
        select: "4%",
        ip: "20%",
        count: "10%",
        lastBlockReason: "24%",
        blockIdentifier: "18%",
        lastBlockTime: "16%",
        actions: "8%",
    },
} satisfies Record<string, TableColumnWidths>
